### ISSUE TITLE
Excuse me, Could you tell me the architecture of your dataset？

### ISSUE THREAD

**Issue by yidamyth** [easternCar/Face-Parsing-Network#3]
Thank you for sharing your code. So sorry, I'm a Newcomer to CV fieldr, Capable of environment configuration. Also download the dataset of CelebAMask-HQ, but can' t run the code ! Because of  i don't konw  your custom dataset -> Class Parse_Dataset: what is like "all_data_path" "gt_data_path" the content. Can you give me an example of a dataset ？thank you very much. I  am looking forward to your reply.

**Comment by easternCar** [comment]
We modified it and uploaded samples of dataset settings.
Sorry for late answer
